# Dockerfile for Angular frontend
FROM node:22.17.1 AS build
WORKDIR /app
COPY bbc-front/ /app/
RUN npm install -g @angular/cli
RUN npm install
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
